### ISSUE TITLE
Prompted for password on every console window open

### ISSUE THREAD

**Issue by thardy** [dahlbyk/posh-sshell#20]
### System Details

- posh-sshell version/path: 0.3.1 / C:\Users\myuser\Documents\WindowsPowerShell\Modules\posh-sshell
- PowerShell version: 5.1.17134.765
- Operating system name and version: Windows 10 1803
- OpenSSH / Putty version: OpenSSH 0.0.1.0

### Issue Description

I am prompted for my ssh password every time I open a console tab in ConsoleZ.  In my personal startup Powershell script, I have...

```
Import-Module posh-git
Import-Module posh-sshell
$Env:HOME = "$Env:USERPROFILE"
Set-Location 'C:\dev'
Start-SshAgent
```

I had to do that HOME reassignment because some unknown process was setting it to "U:".  Getting posh-git to work on windows has been a real beat-down.  It was about hour three before I even discovered posh-sshell.  All my problems have been centered on getting ssh to work on windows.  I remember when getting posh-git working was easy, but the past two times have been a nightmare.

At least I finally got Start-SshAgent working, but I was hoping to not have to enter my password every time I open a new console tab.  If I'm doing something wrong, please help me diagnose.

**Comment by JeremySkinner** [comment]
This isn’t really anything to do with posh-shell. 

The windows version of Openssh contains a windows service that remembers the password once it’s running, so you don’t need to enter the password again. 

- make sure the openssh agent windows service is running 
- use ssh-add to add the key to the agent 
- remove the call to start-sshagent from your poweshell profile.

**Comment by rkeithhill** [comment]
If you use the built-in Windows ssh-agent service then you won't have to enter your password each time the shell starts.  You enter the password once and it will be remembered across restarts.  You do have to make sure the `ssh-agent` service is set to automatic restart and that the service is running.

**Comment by rkeithhill** [comment]
Just beat me to it.  :-)

**Comment by thardy** [comment]
For ssh-agent service, do you mean "OpenSSH Authentication Agent"?

**Comment by rkeithhill** [comment]
Yes.  Once that service is running, use the openssh version of ssh-add.exe to add your private key.  It will prompt you for your passphrase and after that, you won't be prompted again.  Watch out for the spring/fall Windows updates though. They always disable the service so I have to re-enable it after the update.

**Comment by thardy** [comment]
Worked like a charm.  Thanks for your help.  I was going off a set of instructions from a few years back.
