### ISSUE TITLE
It is not clear how I can use the Windows ssh instead of openssh

### ISSUE THREAD

**Issue by ittayd** [dahlbyk/posh-sshell#22]
In the readme it says: "If you are using the Windows-native version of OpenSSH that ships with Windows 10 1803 or newer, ", but it is not clear how I choose this.

**Comment by JeremySkinner** [comment]
It ships pre-installed with newer versions of windows, so it's a case of enabling/starting the OpenSSH Agent windows service (IIRC the agent service is disabled by default), and then running ssh.exe. There's nothing really to "choose" per se.
