### ISSUE TITLE
Tasks for 0.1

### ISSUE THREAD

**Issue by JeremySkinner** [dahlbyk/posh-sshell#5]
- [x] Remove posh-git src and tests
- [x] Split SshUtils.ps1 into separate files
- [x] Copy utility methods that the Ssh Utils need from posh-git
- [x] Add new `Add-PoshSshToProfile` similar to `Add-PoshGitToProfile`
- [x] Tests for ssh functions
- [x] Tests for `Add-PoshSshToProfile`
- [x] Update readme
- [x] Add CI build(s)
- [x] Create publish scripts for gallery

**Comment by the-j0k3r** [comment]
- [ ] fix the readme which is posh git too.

**Comment by JeremySkinner** [comment]
Yep it's already in the list :) Will try and spend some time updating this tonight.

**Comment by the-j0k3r** [comment]
Ah nm I noticed it :) Been looking at pixels all day and have glazed eye balls.
